### ISSUE TITLE
Runtime error with KeOps when I tried to run the sample code

### ISSUE THREAD

**Issue by VElysianP** [jeanfeydy/geomloss#20]
Hi Jean,

Thank you very much for you amazing work. Good luck with your PhD dissertation! 

When I tried to run your sample "plot_optimal_transport_2D.py" with GPU, there is an error that I could not figure out:

#### Error message:
` Traceback (most recent call last):  `
`  File "plot_optimal_transport_2D.py", line 149, in <module>
    gradient_descent( SamplesLoss("sinkhorn", p=2, blur=.1) ) `
`  File "plot_optimal_transport_2D.py", line 107, in gradient_descent
    L_αβ = loss(x_i, y_j) `
`  File "/home/me/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__ `
 `   result = self.forward(*input, **kwargs) `
`  File "/home/me/anaconda3/lib/python3.7/site-packages/geomloss/samples_loss.py", line 237, in forward
    verbose = self.verbose ) `
`  File "/home/me/anaconda3/lib/python3.7/site-packages/geomloss/sinkhorn_samples.py", line 102, in sinkhorn_online
    C_xx, C_yy, C_xy, C_yx, ε_s, ρ, debias=debias ) `
`  File "/home/me/anaconda3/lib/python3.7/site-packages/geomloss/sinkhorn_divergence.py", line 151, in sinkhorn_loop
    a_x = λ * softmin(ε, C_xx, α_log )  # OT(α,α) `
`  File "/home/me/anaconda3/lib/python3.7/site-packages/geomloss/sinkhorn_samples.py", line 69, in softmin_online `
 `   return - ε * log_conv( x, y, f_y.view(-1,1), torch.Tensor([1/ε]).type_as(x) ).view(-1) `
`  File "/home/me/anaconda3/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 351, in __call__
    out = GenredAutograd.apply(self.formula, self.aliases, backend, self.dtype, device_id, ranges, *args) `
 ` File "/home/me/anaconda3/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 43, in forward
    *args) `
` RuntimeError: [KeOps] This KeOps shared object has been compiled without cuda support: try to set tagHostDevice to 0 or recompile the formula with a working version of cuda. `

To test whether I have installed pykeops correctly, I tested the code:

` import torch `
 ` import pykeops.torch as pktorch `

` x = torch.arange(1, 10, dtype=torch.float32).view(-1, 3) `
` y = torch.arange(3, 9, dtype=torch.float32).view(-1, 3) `

` my_conv = pktorch.Genred('SqNorm2(x-y)', ['x = Vi(3)', 'y = Vj(3)']) `
` print(my_conv(x, y)) `

and I received:
#### Error message

` /usr/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported! `
` #error -- unsupported GNU version! gcc versions later than 6 are not supported! `
`  ^~~~~ `
` CMake Error at keopslibKeOpstorch91c92bd508_generated_link_autodiff.cu.o.Release.cmake:219 (message): `
`  Error generating `
`  /home/velysianp/.cache/pykeops-1.2-cpython-37/build- ` 
` libKeOpstorch91c92bd508/CMakeFiles/keopslibKeOpstorch91c92bd508.dir/keops/core/./keopslibKeOpstorch91c92bd508_generated_link_autodiff.cu.o `

` make[3]: ***  [CMakeFiles/keopslibKeOpstorch91c92bd508.dir/keops/core/keopslibKeOpstorch91c92bd508_generated_link_autodiff.cu.o] Error 1 `
` make[2]: *** [CMakeFiles/keopslibKeOpstorch91c92bd508.dir/all] Error 2 `
` make[1]: *** [CMakeFiles/libKeOpstorch91c92bd508.dir/rule] Error 2 `
` make: *** [libKeOpstorch91c92bd508] Error 2 `

Currently I am using **Ubuntu 18.04.3**, with **Python3.7** downloaded from Anaconda. Also, I my GPU is **Geforce 1080** and I downloaded **CUDA 10.2** with its driver and toolkit. The only thing I am worrying about is the gcc version, since now I use "gcc --version" and it returned ` gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0 `. I noticed that CUDA documentation mentioned that the gcc version of Ubuntu 18.04.3 with x86_64 architecture should be 7.3.0. I am wondering if I am having problem with incompatible gcc version with my system that resulted in the problem? Or do you have any other ideas or suggestions? 

Thank you very much. 
Elyson

**Comment by VElysianP** [comment]
Problem solved with reinstall Ubuntu and driver as well as CUDA 10.2. Also, for the installation of KeOps, I found it would be better to use git clone than pip install, since it is easier for me to cmake and change the parameters inside cmake. Anyway, thank you very much for your amazing work!
